name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: # Prevents concurrent runs of the same workflow
  group: ${{ github.workflow }}-${{ github.ref }} # Group runs by workflow and ref
  cancel-in-progress: true # Cancel in-progress runs when a new run is started

# Old workflow for Docker build and push
# jobs:
#    docker-build:
#      runs-on: ubuntu-latest
#      services:
#       mongodb:
#         image: mongo:8
#         ports:
#           - 27017:27017

#      steps:
#      - uses: actions/checkout@v7
     
#      - name: Set up Python 
#        uses: actions/setup-python@v7
#        with:
#          python-version: 3.14

#      - name: Install dependencies
#        run: pip install -r requirements.txt

#      - name: Run tests
#        env:
#           MONGODB_URI: mongodb://localhost:27017
#           MONGODB_DB: todo_app_test

#        run: python -m pytest
     
#      - name: Set image name
#        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

#      - name: Build Docker image
#        run: docker build -t $IMAGE_NAME:latest .
      
#      - name: Log in to ghcr.io
#        if: github.event_name == 'push'
#        uses: docker/login-action@v4
#        with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Push image to ghcr.io
#        if: github.event_name == 'push'
#        run: docker push "$IMAGE_NAME:latest"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
    
    services:
      mongodb:
        image: mongo:8
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.14
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017/
          MONGODB_DB: todo_app_test
        run: python -m pytest

  terraform-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Format Terraform code
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init -backend=false -input=false

      - name: Validate Terraform code
        run: terraform validate
      
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: 
      - test
      - terraform-check
    
    permissions:
      contents: read
      packages: write
  
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v7
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          # Add latest tag if the branch is the default branch
          # Add sha tag for the image
          tags: |
            type=raw,value=latest,enable={{is_default_branch}} 
            type=sha 

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' }} # Push the image to the registry if the event is a push
          tags: ${{ steps.meta.outputs.tags }} # Use the tags from the metadata action
          labels: ${{ steps.meta.outputs.labels }} # Use the labels from the metadata action
          cache-from: type=gha # Use the GHA cache
          cache-to: type=gha,mode=max # Use the GHA cache with max mode